version: '3'
services:
  go:
    #command: /bin/bash -c ' dep ensure && CGO_ENABLED=0 GOOS=linux go build -v -a -installsuffix cgo -o ./main ./main.go'
    command: /bin/bash -c ' cd /go/src/code; dep ensure && CGO_ENABLED=0 GOOS=linux go run Images/main.go'
    build: .
    volumes:
      - .:/go/src
    env_file: .env
    ports:
      - 8080:8080
